In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [71]:
d1=pd.read_csv(r"C:\Users\shubh\OneDrive\Desktop\datasets\Spam1.csv")
d1

     LABEL                                               TEXT URL EMAIL PHONE
0      ham  Your opinion about me? 1. Over 2. Jada 3. Kusr...  No    No    No
1      ham  What's up? Do you want me to come online? If y...  No    No    No
2      ham                       So u workin overtime nigpun?  No    No    No
3      ham  Also sir, i sent you an email about how to log...  No    No    No
4     spam  Please Stay At Home. To encourage the notion o...  No    No    No
...    ...                                                ...  ..   ...   ...
5966   ham                           :( but your not here....  No    No    No
5967   ham  Becoz its  &lt;#&gt;  jan whn al the post ofic...  No    No    No
5968   ham  Its a valentine game. . . send dis msg to all ...  No    No    No
5969   ham                              We r outside already.  No    No    No
5970   ham  The Xmas story is peace.. The Xmas msg is love...  No    No    No

[5971 rows x 5 columns]

In [73]:
d1.tail()

     LABEL                                               TEXT URL EMAIL PHONE
5966   ham                           :( but your not here....  No    No    No
5967   ham  Becoz its  &lt;#&gt;  jan whn al the post ofic...  No    No    No
5968   ham  Its a valentine game. . . send dis msg to all ...  No    No    No
5969   ham                              We r outside already.  No    No    No
5970   ham  The Xmas story is peace.. The Xmas msg is love...  No    No    No

In [75]:
for i in d1.columns:
    if(i != "LABEL" and i!="TEXT"):
        d1.drop(i,axis=1,inplace=True)
d1

     LABEL                                               TEXT
0      ham  Your opinion about me? 1. Over 2. Jada 3. Kusr...
1      ham  What's up? Do you want me to come online? If y...
2      ham                       So u workin overtime nigpun?
3      ham  Also sir, i sent you an email about how to log...
4     spam  Please Stay At Home. To encourage the notion o...
...    ...                                                ...
5966   ham                           :( but your not here....
5967   ham  Becoz its  &lt;#&gt;  jan whn al the post ofic...
5968   ham  Its a valentine game. . . send dis msg to all ...
5969   ham                              We r outside already.
5970   ham  The Xmas story is peace.. The Xmas msg is love...

[5971 rows x 2 columns]

In [77]:
d1.isnull().sum()

LABEL    0
TEXT     0
dtype: int64

In [79]:
d1.LABEL.unique()

array(['ham', 'spam'], dtype=object)

In [81]:
d1.LABEL.value_counts()

LABEL
ham     4844
spam    1127
Name: count, dtype: int64

In [59]:
d2=pd.read_csv(r"C:\Users\shubh\OneDrive\Desktop\datasets\spam.csv",encoding="latin1")#the file wasn't encoded by UTF-8 but by LATIN1 or windows-1252(older files)
d2

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [63]:
for i in d2.columns:
    if(i != "v1" and i!="v2"):
        d2.drop(i,axis=1,inplace=True)
d2

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [65]:
d2.isnull().sum()

v1    0
v2    0
dtype: int64

In [67]:
d2.v1.unique()

array(['ham', 'spam'], dtype=object)

In [69]:
d2.v1.value_counts()

v1
ham     4825
spam     747
Name: count, dtype: int64

In [83]:
d2.rename(columns={"v1": "LABEL", "v2": "TEXT"}, inplace=True)
d2

     LABEL                                               TEXT
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [89]:
df = pd.concat([d1, d2], ignore_index=True)

    df = df.sample(frac=1, random_state=13).reset_index(drop=True)

In [91]:
df

      LABEL                                               TEXT
0       ham  Dude just saw a parked car with its sunroof po...
1       ham  Yeah work is fine, started last week, all the ...
2       ham  That's y i said it's bad dat all e gals know u...
3       ham                       Pls call me da. What happen.
4       ham                   Are u coming to the funeral home
...     ...                                                ...
11538   ham  Guai... Ü shd haf seen him when he's naughty.....
11539   ham  U attend ur driving lesson how many times a wk...
11540   ham  You know there is. I shall speak to you in  &l...
11541   ham  it's still not working. And this time i also t...
11542   ham  If he started searching he will get job in few...

[11543 rows x 2 columns]

In [93]:
df['LABEL'].value_counts()

LABEL
ham     9669
spam    1874
Name: count, dtype: int64

In [95]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['LABEL'] = le.fit_transform(df['LABEL'])  

X = df['TEXT']
y = df['LABEL']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=39,
    stratify=y
)
vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words='english',
    max_features=5000
)
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

print("Train shape:", X_train_vec.shape)
print("Test shape:", X_test_vec.shape)

Train shape: (9234, 5000)
Test shape: (2309, 5000)

In [97]:
from sklearn.utils.class_weight import compute_class_weight

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

class_weights_dict = {i : w for i, w in enumerate(class_weights)}
print(class_weights_dict)

{0: 0.5968972204266322, 1: 3.0800533689126084}

In [103]:
X_train_dense = X_train_vec.toarray()
X_test_dense = X_test_vec.toarray()

print(X_train_dense.shape, X_test_dense.shape)

(9234, 5000) (2309, 5000)

In [111]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Input
from tensorflow.keras.optimizers import Adam

y_train_np = np.array(y_train)
y_test_np = np.array(y_test)

model = Sequential([
    Input(shape=(X_train_dense.shape[1],)),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train_dense, y_train_np,
    validation_data=(X_test_dense, y_test_np),
    epochs=4,
    batch_size=32,
    class_weight=class_weights_dict,
    verbose=1
)

Epoch 1/4
289/289 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8623 - loss: 0.4487 - val_accuracy: 0.9723 - val_loss: 0.0696
Epoch 2/4
289/289 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9888 - loss: 0.0383 - val_accuracy: 0.9879 - val_loss: 0.0453
Epoch 3/4
289/289 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9967 - loss: 0.0129 - val_accuracy: 0.9918 - val_loss: 0.0371
Epoch 4/4
289/289 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9988 - loss: 0.0076 - val_accuracy: 0.9926 - val_loss: 0.0380

In [113]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred_probs = model.predict(X_test_dense)


y_pred = (y_pred_probs >= 0.5).astype(int)

print("Classification Report:")
print(classification_report(y_test_np, y_pred))

cm = confusion_matrix(y_test_np, y_pred)
print("Confusion Matrix:")
print(cm)

73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      1934
           1       0.99      0.97      0.98       375

    accuracy                           0.99      2309
   macro avg       0.99      0.98      0.99      2309
weighted avg       0.99      0.99      0.99      2309


Confusion Matrix:
[[1929    5]
 [  12  363]]